app = 'surtoget'
primary_region = 'arn'

[build]

[http_service]
internal_port = 8000
force_https = true
auto_stop_machines = 'suspend'
auto_start_machines = true
min_machines_running = 0
processes = ['app']

[[vm]]
memory = '512mb'
cpu_kind = 'shared'
cpus = 1
memory_mb = 512

[[http_service.checks]]
grace_period = "5s"
interval = "30s"
method = "GET"
timeout = "5s"
path = "/health"
